FROM alpine:latest

WORKDIR /emscripten
RUN apk add --update --no-cache python2 xz openjdk8-jre wget bash tar && \
    wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz && \
    tar --strip-components=1 -xzvf emsdk-portable.tar.gz && \
    rm emsdk-portable.tar.gz && \
    ./emsdk update && \
    rm -rf /var/cache/apk/*

COPY emsdk.sh /etc/profile.d/emsdk.sh
WORKDIR /
CMD ["/bin/bash", "-l"]
